
name: Container Jobs enter the Matrix 

on: 
  push:
  workflow_dispatch:

jobs:
  Matrix:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['', 'node:latest']
    steps:
      - name: pwd
        run: pwd
      - name: expression value
        run: echo "${{ github.workspace}}"
      - name: env value
        run: echo "$GITHUB_WORKSPACE"
      - name: All env vars
        run: env
